spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jack
    username: root
    password: 1993
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8080