logging:
  level:
    org.hibernate.SQL: trace
    org.hibernate.orm.jdbc.bind: trace
spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/develhope
    username: root
    password: password
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
server:
  port: 8080

