logging:
  level:
    org.hibernate.SQL: trace
    org.hibernate.orm.jdbc.bind: trace
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jack
    username: root
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database: mysql
server:
  port: 8080

